### ISSUE TITLE
Revamp project

### ISSUE THREAD

**Issue by paulhobbel** [ItsDizzy/angular2-auth#17]
I was thinking about changing the project, in means of extending it.
Things I am planning to add:
- Token refresher
- Other token systems
- Better AuthHttp service, which will extend the angular Http service

The current project namespace will be changed to @angular-auth and will get the following modules:
- core - Basicly just the AuthHttp and Token service
- jwt - Adds support for JWT tokens
Each token system will be placed in its own module

This all will be launch as version 0.2.0 and will this time get a proper documentation.

**Comment by paulhobbel** [comment]
## General
- [ ] Create documentation

## Core
- [x] Create `angular-auth` npm organisation
- [ ] Fix annoying `.forRoot` issue mentioned in #14 
- [ ] Rewrite AuthHttp mentioned in #5 
- [ ] Remove JWT leftovers
- [ ] Rewrite Token service to support multiple token types

## JWT
- [ ] Move JWT parts to this module
- [ ] Make tokens "refreshable" if thats even a word as mentioned in #8

**Comment by nimatrazmjo** [comment]
How long it take its to complete
